### ISSUE TITLE
[TextEmoji] Bug: Default emojis in status do not appear

### ISSUE THREAD

**Issue by Inderix** [jedenastka/Aliucord-Plugin-Index#1]
When a user is using a default emoji in their status, instead of rendering an emoji, it acts as if the status has no emoji.

Expected behavior: System default emoji appears in the status

![Screenshot_20240320-071315.png](https://github.com/jedenastka/Aliucord-Plugin-Index/assets/88416096/215099d0-4597-498e-b13a-51eb17ee0852)

![Screenshot_20240320-071331.png](https://github.com/jedenastka/Aliucord-Plugin-Index/assets/88416096/35d15c99-1d64-4932-b940-d13a54ac6aa3)

**Comment by jedenastka** [comment]
Please open an issue against the [TextEmoji repository](https://gitlab.com/Grzesiek11/textemoji-aliucord-plugin), thanks!

**Comment by jedenastka** [comment]
Are you planning on opening an issue on that repo, or should I do that?

**Comment by Inderix** [comment]
i forgor 💀

**Comment by jedenastka** [comment]
Did you rember?
